# Generated by Django 2.2.4 on 2019-08-21 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190821_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpformmodel',
            name='when',
            field=models.DateField(default=datetime.datetime(2019, 8, 21, 23, 51, 26, 213157, tzinfo=utc)),
        ),
    ]
