# Generated by Django 2.2.4 on 2019-08-26 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190823_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=50)),
                ('date_uploaded', models.DateField(default=datetime.datetime(2019, 8, 26, 0, 21, 43, 530049, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='when',
            field=models.DateField(default=datetime.datetime(2019, 8, 26, 0, 21, 43, 529724, tzinfo=utc)),
        ),
    ]
