# Generated by Django 2.2.4 on 2019-08-27 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20190825_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(default='logo.png', upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 27, 0, 17, 0, 262701, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='when',
            field=models.DateField(default=datetime.datetime(2019, 8, 27, 0, 17, 0, 262283, tzinfo=utc)),
        ),
    ]
