# Generated by Django 2.2.4 on 2019-08-27 23:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20190827_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoformmodel',
            name='thumb',
        ),
        migrations.AddField(
            model_name='faqformmodel',
            name='question',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='videoformmodel',
            name='vid_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='videoformmodel',
            name='vid_url',
            field=models.URLField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 27, 23, 21, 3, 489964, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='when',
            field=models.DateField(default=datetime.datetime(2019, 8, 27, 23, 21, 3, 489669, tzinfo=utc)),
        ),
    ]
