# Generated by Django 2.2.4 on 2019-08-28 02:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20190827_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpformmodel',
            name='when',
        ),
        migrations.RemoveField(
            model_name='videoformmodel',
            name='vid_url',
        ),
        migrations.AddField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 36, 10, 292723, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='videoformmodel',
            name='youtube_unique_code',
            field=models.URLField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 36, 10, 293029, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='subject',
            field=models.CharField(choices=[('ipad', 'ipad'), ('mac', 'mac'), ('keynote', 'keynote'), ('pages', 'pages'), ('imovie', 'imovie'), ('schoology', 'schoology'), ('other', 'other')], default='other', max_length=10),
        ),
    ]
