# Generated by Django 2.2.4 on 2019-08-28 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20190828_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 37, 26, 211105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='subject',
            field=models.CharField(choices=[('Ipad', 'ipad'), ('Mac', 'mac'), ('Keynote', 'keynote'), ('Pages', 'pages'), ('Imovie', 'imovie'), ('Schoology', 'schoology'), ('Other', 'other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 37, 26, 210802, tzinfo=utc)),
        ),
    ]
