# Generated by Django 2.2.4 on 2019-08-28 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20190828_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 37, 55, 534052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='subject',
            field=models.CharField(choices=[('ipad', 'Ipad'), ('mac', 'mac'), ('keynote', 'keynote'), ('pages', 'pages'), ('imovie', 'imovie'), ('schoology', 'schoology'), ('other', 'other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 37, 55, 533757, tzinfo=utc)),
        ),
    ]
