# Generated by Django 2.2.4 on 2019-08-28 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20190828_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 38, 34, 304541, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='subject',
            field=models.CharField(choices=[('ipad', 'Ipad'), ('mac', 'Mac'), ('keynote', 'Keynote'), ('pages', 'Pages'), ('imovie', 'Imovie'), ('schoology', 'Schoology'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 38, 34, 304197, tzinfo=utc)),
        ),
    ]
