# Generated by Django 2.2.4 on 2019-08-28 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20190828_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 48, 27, 362350, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 2, 48, 27, 362003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='email',
            field=models.EmailField(default='@k12.wv.us', max_length=254),
        ),
    ]
