# Generated by Django 2.2.4 on 2019-08-28 23:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20190828_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 23, 51, 19, 965965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 23, 51, 19, 965653, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videoformmodel',
            name='youtube_unique_code',
            field=models.CharField(max_length=18),
        ),
    ]
