# Generated by Django 2.2.4 on 2019-08-28 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20190828_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 23, 55, 54, 820900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 8, 28, 23, 55, 54, 820575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videoformmodel',
            name='youtube_unique_code',
            field=models.URLField(max_length=30),
        ),
    ]
