# Generated by Django 2.2.4 on 2019-09-08 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20190828_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 0, 41, 10, 507147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 0, 41, 10, 506846, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='videoformmodel',
            name='youtube_unique_code',
            field=models.CharField(max_length=11),
        ),
    ]
