# Generated by Django 2.2.4 on 2019-09-08 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20190908_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoformmodel',
            name='subject',
            field=models.CharField(choices=[('ipad', 'Ipad'), ('mac', 'Mac'), ('keynote', 'Keynote'), ('pages', 'Pages'), ('imovie', 'Imovie'), ('schoology', 'Schoology'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 1, 0, 55, 674617, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 9, 8, 1, 0, 55, 674300, tzinfo=utc)),
        ),
    ]
