# Generated by Django 2.2.4 on 2019-09-11 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20190908_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqformmodel',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faqformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 0, 12, 59, 808438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='date_uploaded',
            field=models.DateField(default=datetime.datetime(2019, 9, 11, 0, 12, 59, 808131, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='helpformmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videoformmodel',
            name='vid_name',
            field=models.CharField(default='Core Help-', max_length=50),
        ),
    ]
